export const el = {
  statusCard: document.querySelector("#status-card"),
  statusTitle: document.querySelector("#status-title"),
  statusDetail: document.querySelector("#status-detail"),
  stats: {
    systems: document.querySelector("#stat-systems"),
    sites: document.querySelector("#stat-sites"),
    innerBelts: document.querySelector("#stat-inner-belts"),
    outerBelts: document.querySelector("#stat-outer-belts"),
  },
  searchInput: document.querySelector("#search-input"),
  searchSuggestions: document.querySelector("#search-suggestions"),
  regionSelect: document.querySelector("#region-select"),
  candidateRadius: document.querySelector("#candidate-radius"),
  candidateRadiusHint: document.querySelector("#candidate-radius-hint"),
  cometOnly: document.querySelector("#comet-only"),
  combatOnly: document.querySelector("#combat-only"),
  innerBeltOnly: document.querySelector("#inner-belt-only"),
  outerBeltOnly: document.querySelector("#outer-belt-only"),
  resetButton: document.querySelector("#reset-button"),
  detailTitle: document.querySelector("#detail-title"),
  detailRegion: document.querySelector("#detail-region"),
  detailEmpty: document.querySelector("#detail-empty"),
  detailContent: document.querySelector("#detail-content"),
  nearbySystems: document.querySelector("#nearby-systems"),
  systemReport: document.querySelector("#system-report"),
  siteListNotes: document.querySelector("#site-list-notes"),
  siteList: document.querySelector("#site-list"),
};
